[workspace]
members = [
    "hacspec-lib",
    "hacspec-dev",
    "hacspec-derive",
    "hacspec",
    "secret-integers",
    "abstract-integers",
    "hacspec-examples/hacspec-chacha20",
    "spec-examples",
    "hacspec-attributes",
    "hacspec-sig"
]
default-members = [
    "hacspec-lib",
    "hacspec-dev",
    "hacspec-derive",
    "secret-integers",
    "abstract-integers",
    "hacspec-examples/hacspec-chacha20",
    "spec-examples",
    "hacspec-attributes",
    "hacspec-sig"
]
