
[workspace]
members = [
    "hacspec",
    "hacspec-dev",
    "hacspec-derive",
    "hacspec-lang",
    "secret-integers",
    "abstract-integers",
    "spec-examples",
    "attributes",
]
default-members = [
    "hacspec",
    "hacspec-dev",
    "hacspec-derive",
    "secret-integers",
    "abstract-integers",
    "spec-examples",
    "attributes",
]
