[workspace]
members = [
    "hacspec-lib",
    "hacspec-dev",
    "hacspec-derive",
    "hacspec",
    "secret-integers",
    "abstract-integers",
    "hacspec-examples/hacspec-chacha20",
    "hacspec-examples/hacspec-poly1305",
    "hacspec-examples/hacspec-chacha20poly1305",
    "unsafe-hacspec-examples",
    "hacspec-attributes",
    "hacspec-sig"
]
default-members = [
    "hacspec-lib",
    "hacspec-dev",
    "hacspec-derive",
    "secret-integers",
    "abstract-integers",
    "hacspec-examples/hacspec-chacha20",
    "hacspec-examples/hacspec-poly1305",
    "hacspec-examples/hacspec-chacha20poly1305",
    "unsafe-hacspec-examples",
    "hacspec-attributes",
    "hacspec-sig"
]

[profile.release]
debug = true
