[package]
name = "hacspec-provider"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evercrypt = "0.0.1"
hacspec-lib = { path = "../../lib" }
hacspec-chacha20poly1305 = { path = "../../examples/hacspec-chacha20poly1305" }
hacspec-chacha20 = { path = "../../examples/hacspec-chacha20" }
hacspec-poly1305 = { path = "../../examples/hacspec-poly1305" }

[dev-dependencies]
rand = "0.7"
