name: Build & Test

on: [push, pull_request, release]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: rustup toolchain install nightly && rustup toolchain install nightly
    - name: Build
      run: cargo build +nightly --verbose
    - name: Run tests
      run: cargo test +nightly --verbose
    - name: Get hacspec function stats
      run: bash hacspec/get_func_stats.sh
      env:
        RUST_NIGHTLY: nightly
