name: Build & Test

on: [push, pull_request, release]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Prepare
      run: rustup toolchain install nightly-2021-02-14 && rustup default nightly-2021-02-14 && rustup component add --toolchain nightly-2021-02-14 rustc-dev && rustup component add --toolchain nightly-2021-02-14 llvm-tools-preview
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Test Provider
      run: cargo test --verbose -p rc-tests
    - name: Get hacspec function stats
      run: RUST_NIGHTLY=nightly-2021-02-14 ./lib/get_func_stats.sh
    - name: Build and test F* compiler
      run: cargo clean && cd language && cargo +nightly-2021-02-14 test --verbose
